### ISSUE TITLE
typo in read-me

### ISSUE THREAD

**Issue by tdcwilliams** [pderian/NEMOGCM-Docker#2]
Hi @pderian,

one small typo the read-me file:
`cd ..; cp arch_NEMOGCM/arch* SRC/NEMOGCM/ARCH; cp arch_XIOS/arch* SRC/XIOS/ARCH`
should be
`cd ..; cp arch_NEMOGCM/arch* SRC/NEMOGCM/ARCH; cp arch_XIOS/arch* SRC/XIOS/arch`

Otherwise it worked perfectly - thanks!

**Comment by pderian** [comment]
Hi @tdcwilliams,

I trust you on this, I have not used NEMO in a couple years. Typo is fixed, thanks!

On a side note I'm glad it still works. Out of curiosity, did you use a recent release of NEMO (I just checked and it seems to be 4.0 now whereas back then I used 3.6)?

**Comment by tdcwilliams** [comment]
hi @pderian, I just used version 3.6 as you had it  - we are still on nemo 3 as well for the moment.
